const imageUrl = "https://ripples1static.blob.core.windows.net/images/images/";

export const imageUrls = {
  analyticsPerformanceCard: imageUrl + "analyticsPerformanceCard.png",
  backgroundImage: imageUrl + "backgroundImage.png",
  benefitsSectionImage: imageUrl + "benefitsSectionImage.png",
  bottomSectionImage: imageUrl + "bottomSectionImage.png",
  campaign: imageUrl + "campaign.webp",
  cashback: imageUrl + "cashback.png",
  coins: imageUrl + "coins.webp",
  contactus: imageUrl + "contactus.webp",
  customerView: imageUrl + "customerView.webp",
  data_privacy: imageUrl + "data_privacy.png",
  discountCodeToggle: imageUrl + "discountCodeToggle.webp",
  editShare: imageUrl + "editShare.webp",
  flayer: imageUrl + "flayer.webp",
  flayer2: imageUrl + "flayer2.png",
  link: imageUrl + "link.webp",
  linkModal: imageUrl + "linkModal.png",
  
  milestone: imageUrl + "milestone.png",
  notFound: imageUrl + "not-found.svg",
  promoImg: imageUrl + "promoImg.png",
  referral_icon: imageUrl + "referral-icon.svg",
  referralApp: imageUrl + "referralApp.svg",
  rewardmanage: imageUrl + "rewardmanage.svg",
  rupees: imageUrl + "rupees.webp",
  shopify_plus: imageUrl + "shopify plus.png",
  shopify: imageUrl + "shopify.png",
  shopperPageFlayer: imageUrl + "shopperPageFlayer.png",
  step1: imageUrl + "step1.png",
  step2: imageUrl + "step2.png",
  step3: imageUrl + "step3.png",
  ugc_icon: imageUrl + "ugc-icon.svg",
  ugcContentBottomGradientEffect:
    imageUrl + "ugcContentBottomGradientEffect.svg",
  ugcContentManagementCard: imageUrl + "ugcContentManagementCard.png",
  ugcPopup: imageUrl + "ugcPopup.png",
  wallet: imageUrl + "wallet.svg",
  avatar: {
    avatar1: imageUrl + "avatars/avatar1.png",
    avatar2: imageUrl + "avatars/avatar2.png",
    avatar3: imageUrl + "avatars/avatar3.png",
  },
  benefitSectionIcons: {
    bicon1: imageUrl + "benefitSectionIcons/bicon1.png",
    bicon2: imageUrl + "benefitSectionIcons/bicon2.png",
    bicon3: imageUrl + "benefitSectionIcons/bicon3.png",
    bicon4: imageUrl + "benefitSectionIcons/bicon4.png",
  },
  brands: {
    accenture: imageUrl + "brands/accenture.png",
    cred: imageUrl + "brands/cred.png",
    shopify: imageUrl + "brands/shopify.png",
    udaan: imageUrl + "brands/udaan.png",
  },
  founders: {
    pranav: imageUrl + "founders/pranav.png",
    tazril: imageUrl + "founders/tazril.jpeg",
  },
  login: {
    gift1: imageUrl + "login/gift1.webp",
    gift2: imageUrl + "login/gift2.webp",
    gift3: imageUrl + "login/gift3.webp",
    loginBg: imageUrl + "login/login-bg.webp",
  },
  profilePicture: {
    profile1: imageUrl + "profilePics/profilepic1.jpg",
    profile2: imageUrl + "profilePics/profilepic2.jpg",
    profile3: imageUrl + "profilePics/profilepic3.jpg",
  },
};
